services:
  pythonapp:
    build: .
    # command: sh -c "sleep 10s ; uvicorn app:app --reload;"
    ports:
      - "8000:8000"
    depends_on:
      - db1
  db1:
    build:
      context: .
      dockerfile: Dockerfile_sql
    container_name: "my-db-1"
    restart: always
    environment:
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "db"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_HOST: "%"
    ports:
      - "6033:3306"