create table if not exists restaurant_db(
	url varchar(255),
	restaurant_id varchar(50) primary key,
	fetch_count int,
	time_of_fetching_data varchar(100),
	rating float,
	rest_name varchar(255),
	address varchar(255),
	telephone varchar(255),
	website varchar(255),
	tags varchar(255),
	CUISINES varchar(255),
	Special_Diets varchar(255),
	Meals varchar(255),
	is_michelin varchar(3),
	menu_link_available varchar(3),
	neighborhood varchar(255),
	restaurant_rank varchar(255),
	Food_Rating float,
	Value_Rating float,
	Service_Rating float,
	Atmosphere_Rating float,
	PRICE_RANGE varchar(100),
	FEATURES text,
	total_reviews int,
	menu_link varchar(255),
	geo_id varchar(20)
);

