create table if not exists restaurant_db(
	url text,
	restaurant_id text,
	fetch_count bigint,
	time_of_fetching_data text,
	rating double,
	rest_name text,
	address text,
	telephone text,
	website text,
	tags text,
	CUISINES text,
	Special_Diets text,
	Meals text,
	is_michelin text,
	menu_link_available text,
	neighborhood text,
	restaurant_rank text,
	Food_Rating double,
	Value_Rating double,
	Service_Rating double,
	Atmosphere_Rating double,
	PRICE_RANGE text,
	FEATURES text,
	total_reviews bigint,
	menu_link text,
	geo_id bigint
);

